name: 'Gitbook-Action'

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'  # To Avoid Loop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v2

      - name: Gitbook Action
        uses: ZanderZhao/gitbook-action@master
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          source_branch: main
          source_dir: src
          source_edit_time: true
          publish_commit_message: ${{ github.event.head_commit.message }}
          publish_branch: main
          publish_dir: docs
          publish_push_force: true
          publish_nojekyll: true
